transferzero/transferzero-sdk-java8

example/src/main/java/com/transferzero/test/Application.java
Tidying up ruby examples:
- spelling correction.
=> BTA-1681-clean-up-sdks-for-an-1.0.0-release

pom.xml
This PR updates `pom.xml` that was auto-updated when releasing package
=> BTA-2497 releases

build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/api/DocumentsApiTest.java, src/test/java/com/transferzero/sdk/model/DocumentTest.java, src/test/java/com/transferzero/sdk/model/PayinMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/SenderTest.java
BTA-3102 Regenerate SDK 1.6.0
Changes
-------
Changes made using the open-api generator locally in this specific project as some of the files were not getting generated by the generator ran by [Travis commit.](https://github.com/transferzero/transferzero-sdk-java8/commit/672a3bec9d3a30e77d0afac650d0756f15e2f939)
Risk and impact assessment
--------------------------
The following PR contains (please tick anything that applies):
=> BTA-3102 SDK version manual regenerate and release

README.md
=> BTA-3102 Update README

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/api/RecipientsApiTest.java, src/test/java/com/transferzero/sdk/model/DocumentTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/SenderTest.java
BTA-3139 Regenerate SDK 1.7.0
Changes
-------
Changes made using the open-api generator locally in this specific project as some of the files were not getting generated by the generator ran by Travis
=> BTA-3139 Update Java8 SDK version to v1.7.0 

pom.xml
This PR updates `pom.xml` that was auto-updated when releasing package
=> BTA-3139: Releases

README.md, build.gradle, pom.xml, src/test/java/com/transferzero/sdk/model/CurrencyOppositeTest.java, src/test/java/com/transferzero/sdk/model/CurrencyTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsZARBankTest.java, src/test/java/com/transferzero/sdk/model/SenderTest.java
[BTA-3866](https://azafinance.atlassian.net/browse/BTA-3866) Regenarating SDK from v1.7.1 to v1.8.0 SDK for the missing change skipped by the Travis commit.
- The change of `coreBusinessActivities` to `coreBusinessActivity ` was an update on this [PR](https://github.com/bitpesa/bitpesa-api-specification/pull/209).
=> BTA-3866 Update SDK from v1.7.1 to v1.8.0

pom.xml
Changes from mvn release:prepare
=> BTA-5293 release transferzero sdk java8 to maven

pom.xml
Changes from mvn release:prepare
=> BTA-5631 release transferzero sdk java8 to maven v11.0.0

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsXOFMobileTest.java
Prepare SDK for release to Maven
=> BTA-5456 Release `1.13.0`

README.md, build.gradle, build.sbt, pom.xml
=> BTA-6733 Release 1.14.0

README.md, build.gradle, build.sbt, pom.xml
=> BTA-6773 Release 1.14.1

README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/transferzero/sdk/ApiClient.java
ticket: https://azafinance.atlassian.net/browse/BTA-6591
=> BTA-6591 Release java sdk version 1.15.0

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/RecipientTest.java
[BTA-7084](https://azafinance.atlassian.net/browse/BTA-7084): Update API documentation for Recipient type
Changes
---------
- Regenerated SDK with latest changes (version '1.16.1').
=> Regenerated SDK with latest changes (version '1.16.1')

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/DocumentTest.java, src/test/java/com/transferzero/sdk/model/PayinMethodDetailsMobileTest.java, src/test/java/com/transferzero/sdk/model/PayinMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/PayinMethodTest.java, src/test/java/com/transferzero/sdk/model/RecipientStateReasonDetailsTest.java, src/test/java/com/transferzero/sdk/model/SenderTest.java
Regenerate SDK to version 1.19.0
=> BTA-7797 Regenerate SDK with 1.19.0 updating PayinMethod

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java
=> BTA-9540 1.23.0 release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsZARBankTest.java
=> BTA-11126 1.27.5 Release

.github/workflows/release.yml, pom.xml
Add a workflow that deploys the SDK to maven repository
=> BTA-11168 add a workflow that deploys the SDK to maven repository

pom.xml
BTA-11168 Update the pom.xml file with GPG passphrase
=> BTA-11168 Update the pom.xml file with GPG passphrase

README.md, build.gradle, build.sbt, pom.xml
=> BTA-11584 1.27.9 Release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsKESMobileTest.java
=> BTA-11542 1.28.0 Release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsBRLBankTest.java
=> 1.28.2 Release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/AccountTest.java
=> BTA-11835 1.29.0 Release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java
BTA-12238 SDK version 1.30.0 Release
=> BTA-12238 SDK version 1.30.0 Release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsEGPBankTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsUGXBankTest.java
=> v1.30.2-release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsGBPBankTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsIBANTest.java
=> BTA-12330-1.30.3-release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsZARBankTest.java
=> BTA-12471-release 1.33.1

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsUSDBankTest.java
=> BTA-12546 1.34.0 release

README.md, build.gradle, build.sbt, pom.xml
BTA-13014 Version 1.34.1 release
=> BTA-13014 Version 1.34.1 release

README.md, build.gradle, build.sbt, pom.xml
=> BTA-13332 Release 1.34.3

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayinMethodDetailsNGNBankTest.java
=> Release 1.36.0

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsEGPCashTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java
BTA-14455-version-1.36.3-release
=>  BTA-14455-version-1.36.3-release

README.md, build.gradle, build.sbt, pom.xml
BTA-14549-version-1.36.4-release
=> BTA-14549-version-1.36.4-release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsGHSBankTest.java, src/test/java/com/transferzero/sdk/model/PayoutMethodDetailsTest.java
BTA-15195-version-1.36.7-release
=> BTA-15195-version-1.36.7-release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/AccountValidationResultTest.java
BTA-15286-version-1.36.8-release
=> BTA-15286-version-1.36.8-release

README.md, build.gradle, build.sbt, pom.xml, src/test/java/com/transferzero/sdk/model/PayinMethodDetailsNGNBankTest.java
BTA-15646-version-1.37.1-release
=> BTA-15646-version-1.37.1-release
